### ISSUE TITLE
ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by yukirii** [latency-at/datadog-agent-prometheus#7]
Hi.

I'm trying to run this check in our Kubernetes cluster. I'm using datadog-agent v5.22.3 installed by helm (datadog chart [v0.10.9](https://github.com/kubernetes/charts/blob/05a85e81afb9c4640b7efbef6c0abdf823d79097/stable/datadog/Chart.yaml)).

When I installed check script and run it, I received error that is `ValueError: need more than 1 value to unpack`.

Here is error logs:
`# service datadog-agent info`
```
  prometheus (custom)
  -------------------
    - instance #0 [ERROR]: 'need more than 1 value to unpack'
    - Collected 0 metrics, 0 events & 0 service checks
```

`/var/log/datadog/collector.log`
```
2018-03-28 09:18:35 UTC | ERROR | dd.collector | checks.prometheus(__init__.py:829) | Check 'prometheus' instance #0 failed
Traceback (most recent call last):
  File "/opt/datadog-agent/agent/checks/__init__.py", line 812, in run
    self.check(copy.deepcopy(instance))
  File "/etc/dd-agent/checks.d/prometheus.py", line 86, in check
    instance=instance)
  File "/etc/dd-agent/checks.d/prometheus.py", line 61, in process
    content_type, data = self.poll(endpoint, headers=headers, pFormat=format)
ValueError: need more than 1 value to unpack
```

According to `PrometheusScraper` implementation, `poll()` [returns a `requests.Responce` object](https://github.com/DataDog/dd-agent/blob/master/checks/prometheus_mixins.py#L427) and `parse_metric_family()` [can recieve it](https://github.com/DataDog/dd-agent/blob/master/checks/prometheus_mixins.py#L142).

So I changed the way to receive return value and pass arguments:

```diff
61c61
<         content_type, data = self.poll(endpoint, headers=headers, pFormat=format)
---
>         resp = self.poll(endpoint, headers=headers, pFormat=format)
64c64
<                 self.parse_metric_family(data, content_type)):
---
>                 self.parse_metric_family(resp)):
```

Then, the check works well and I confirmed that metrics is shown in Datadog Metrics Explorer. But I don’t know that it is the right solution.
Would it be ok to fix the code like this?

**Comment by yukirii** [comment]
I also received a similar error under datadog-agent version 6 (datadog chart v0.10.11):

`# agent status`
```
  prometheus
  ----------
    Total Runs: 6
    Metrics: 0, Total Metrics: 0
    Events: 0, Total Events: 0
    Service Checks: 0, Total Service Checks: 0Error: too many values to unpack
    Traceback (most recent call last):
      File "/opt/datadog-agent/bin/agent/dist/checks/__init__.py", line 332, in run
        self.check(copy.deepcopy(self.instances[0]))
      File "/etc/datadog-agent/checks.d/prometheus.py", line 86, in check
        instance=instance)
      File "/etc/datadog-agent/checks.d/prometheus.py", line 61, in process
        content_type, data = self.poll(endpoint, headers=headers, pFormat=format)
    ValueError: too many values to unpack
```

`/var/log/datadog/agent.log`
`2018-03-28 09:21:12 UTC | ERROR | (runner.go:276 in work) | Error running check prometheus: [{"message": "too many values to unpack", "traceback": "Traceback (most recent call last):\n  File \"/opt/datadog-agent/bin/agent/dist/checks/__init__.py\", line 332, in run\n    self.check(copy.deepcopy(self.instances[0]))\n  File \"/etc/datadog-agent/checks.d/prometheus.py\", line 86, in check\n    instance=instance)\n  File \"/etc/datadog-agent/checks.d/prometheus.py\", line 61, in process\n    content_type, data = self.poll(endpoint, headers=headers, pFormat=format)\nValueError: too many values to unpack\n"}]`

**Comment by discordianfish** [comment]
Okay, looks like DD changed PrometheusScraper. Your fix looks good. If you submit a PR I'm happy to merge it!
